general:
  clustered_gtf:
  data_dir:
  five_prime_regulatory_nts: 1000
  gtf:
  gtf_cluster_min_gap: 2000
  gtf_header: 4
  init_bedtools: module load bedtools
  n_gtf_clusters:
  three_prime_regulatory_nts: 1000
  tmp_dir:
pas_atlas:
  pas_atlas_path:
smeagol:
  genome_fasta:
  motif_dir:
  predict_rbp_binding_in: UTR
  threshold: 0.8
targetscan:
  target_locations_GRCh38_bed:
  target_locations_hg19_bed:
tcga_mc3:
  cosmic_msi_sbs:
  - SBS6
  - SBS14
  - SBS15
  - SBS20
  - SBS21
  - SBS22
  - SBS26
  - SBS44
  cosmic_pole_sbs:
  - SBS10a
  - SBS10b
  mc3_GRCh37_maf:
  mc3_GRCh38_maf:
  tcga_code_tables:
  tcga_ids_path:
  tcga_sbs_path:
  ucsc_liftover: /data/archiv/SCC/ag-gruber/jthorwarth/SOFTWARE/UCSC_TOOLS/liftOver
  ucsc_liftover_chainfile:
uniprotkb:
  ensembl_sprot_map:
  sprot_xml:
visualization:
  figure_style_dict:
    add_gtf_cluster:
      CDS_height_ratio: 0.7
      color: rgba(0,0,100,1.0)
      intron_height_ratio: 0.02
      line_width: 1.0
      other_feature_height_ratio: 0.02
      regulatory_sequence_fill_color: null
      regulatory_sequence_height_ratio: 0.02
      regulatory_sequence_line_color: null
      row_height: 0.5
      utr_height_ratio: 0.3
      start_codon_color: rgba(0,250,0,1.0)
      start_codon_height_ratio: 0.7
      stop_codon_color: rgba(250,0,0,1.0)
      stop_codon_height_ratio: 0.7
    add_gtf_collapsed_genes:
      CDS_height_ratio: 0.7
      color: rgba(0,0,0,1.0)
      five_prime_regulatory_sequence_height_ratio: 0.02
      five_prime_utr_height_ratio: 0.3
      intron_height_ratio: 0.02
      other_feature_height_ratio: 0.02
      regulatory_sequence_height_ratio: 0.02
      row_height: 0.25
      three_prime_regulatory_sequence_height_ratio: 0.02
      three_prime_utr_height_ratio: 0.3
      utr_height_ratio: 0.3
      start_codon_color: rgba(0,250,0,1.0)
      start_codon_height_ratio: 0.7
      stop_codon_color: rgba(250,0,0,1.0)
      stop_codon_height_ratio: 0.7
    add_gtf_transcript_features:
      CDS_height_ratio: 0.7
      color: rgba(0,0,0,1.0)
      five_prime_regulatory_sequence_height_ratio: 0.02
      five_prime_utr_height_ratio: 0.3
      regulatory_sequence_height_ratio: 0.02
      row_height: 0.25
      start_codon_height_ratio: 0.7
      stop_codon_height_ratio: 0.3
      three_prime_regulatory_sequence_height_ratio: 0.02
      three_prime_utr_height_ratio: 0.3
      transcript_height_ratio: 0.02
      utr_height_ratio: 0.3
    add_miRNA_binding:
      color: rgba(177, 7, 0, 1.0)
      height_ratio: 0.9
      row_height: 0.25
    add_mutations:
      DEL_color: '#66a61e'
      INS_color: '#e6ab02'
      SNP_color: '#e7298a'
      height_ratio: 0.9
      row_height: 2.0
    add_pas:
      cleavage_site_height_ratio: 0.45
      color: rgba(100,10,150,1.0)
      connection_height_ratio: 0.03
      row_height: 0.25
      signal_height_ratio: 0.9
    add_rbp_binding:
      color: rgba(0, 150, 50, 1.0)
      height_ratio: 0.9
      row_height: 0.25
